-- Refresh the store catalog with the new sellable product line.
-- We INSERT … ON CONFLICT to keep this idempotent: existing slugs are updated;
-- new ones are added; old ones not in this list are left in place (not removed)
-- so any in-flight orders remain consistent.

-- Helper: drop any old rows we are about to re-insert (so totals match).
DELETE FROM store_product WHERE slug IN (
    'spring-boot-microservices-kit',
    'photo-sorter-pro',
    'hospital-management-system',
    'hotel-booking-platform',
    'pharmacy-management-system',
    'salon-spa-management',
    'appointment-booking-engine',
    'invoice-gst-management',
    'shivhari-dev-template',
    'autoscalp-bot',
    'cafe-pos',
    'workiva-toolkit'
);

INSERT INTO store_product
(slug, title, tagline, description, category, price_inr, price_usd, cover_color, tags, features, what_you_get, tech_stack, file_size_mb, version, demo_url, repo_url, featured)
VALUES
('hospital-management-system',
 'Hospital Management System',
 'Multi-department hospital OS — OPD, IPD, billing, lab, pharmacy, doctor schedules, patient records.',
 'Full operational stack for clinics and mid-size hospitals. Production-grade auth, role-based access for doctors/nurses/admins/cashiers, lab report uploads, prescription workflow, and a billing module that handles cash, insurance, and corporate clients. Multi-tenant ready out of the box.',
 'Healthcare', 24999, 299, '#a855f7',
 'Spring Boot,React,PostgreSQL,HL7',
 'OPD + IPD with bed allocation|Doctor scheduling & queue|Lab module with report upload|In-house pharmacy + inventory|Insurance + corporate billing|Multi-tenant + role-based access',
 'Complete source (Spring Boot + React)|Sample seed for a 30-bed hospital|Postman + API docs|Setup video walkthrough|Email support 60 days',
 'Java 17,Spring Boot 3,React 18,PostgreSQL,JWT auth,Docker',
 92, '2.1.0', NULL, NULL, TRUE),

('hotel-booking-platform',
 'Hotel Booking Platform',
 'Direct-booking engine for boutique hotels — rooms, rates, channel sync, dynamic pricing, payments.',
 'Take direct bookings on your own website instead of paying OTA commissions. Built-in channel sync to Booking.com / Airbnb / MakeMyTrip. Dynamic pricing, seasonal rates, guest profiles, and invoice + GST generation.',
 'Hospitality', 19999, 249, '#38bdf8',
 'Next.js,Stripe,Postgres,Channel API',
 'Room inventory + dynamic pricing|Channel sync (Booking/Airbnb/MMT)|Direct payments (Razorpay + Stripe)|Guest profiles + repeat-stay tracking|GST-ready invoicing|Multi-property support',
 'Complete source|Seed for sample 12-room property|Channel sync starter kit|Setup guide + walkthrough',
 'Next.js 14,Node 20,PostgreSQL,Razorpay,Stripe',
 58, '1.4.0', NULL, NULL, TRUE),

('pharmacy-management-system',
 'Pharmacy Management System',
 'Retail-pharmacy POS — inventory, batch + expiry tracking, prescription upload, GST invoices.',
 'Built for Indian retail pharmacies. Batch-and-expiry inventory, prescription image upload + retrieval, GST-ready invoicing, supplier purchase orders, and a customer profile for repeat prescriptions.',
 'Healthcare', 14999, 179, '#10b981',
 'React,Spring Boot,PostgreSQL,Barcode',
 'Batch + expiry tracking|Barcode scanner support|Prescription image upload|GST-compliant invoicing|Supplier purchase orders|Customer profile + repeat Rx',
 'Complete source|Sample drug master CSV|Setup guide|Email support 30 days',
 'React,Spring Boot 3,PostgreSQL,Tailwind',
 44, '1.3.0', NULL, NULL, TRUE),

('salon-spa-management',
 'Salon & Spa Management',
 'Booking + staff schedules + service catalog for salons and spas. WhatsApp reminders included.',
 'Front-desk workflow for salons and spas — staff schedules, service catalog with packages, WhatsApp reminders, walk-in queue, and a customer profile that tracks preferences and stylist history.',
 'Business Tools', 7999, 99, '#ec4899',
 'React,Node,PostgreSQL,WhatsApp',
 'Staff scheduling + commission tracking|Service catalog with packages|WhatsApp + SMS reminders|Walk-in queue management|Customer profile + visit history|Daily/weekly reports',
 'Complete source code|Sample salon seed data|WhatsApp setup guide|Setup video walkthrough',
 'React,Node 20,PostgreSQL,Twilio WhatsApp',
 32, '1.0.2', NULL, NULL, TRUE),

('appointment-booking-engine',
 'Appointment Booking Engine',
 'Plug-and-play appointment booking — clinics, consultants, coaches, beauticians.',
 'A clean booking widget you can drop into any site. Calendar sync (Google + iCal), Twilio reminders, no-show flagging, configurable buffer time, and payment-on-booking via Razorpay/Stripe.',
 'Business Tools', 4999, 59, '#fbbf24',
 'Next.js,iCal,Twilio,Postgres',
 'Drop-in booking widget|Google + iCal calendar sync|Twilio SMS + WhatsApp reminders|No-show flagging|Pay-on-booking (Razorpay/Stripe)|Buffer time + lunch breaks',
 'Complete source|Embed snippets (React/HTML)|Setup guide|Email support 30 days',
 'Next.js 14,PostgreSQL,Twilio,Razorpay',
 18, '1.2.0', NULL, NULL, TRUE),

('invoice-gst-management',
 'Invoice & GST Management',
 'Invoicing for Indian SMEs — GST-compliant, e-invoice IRN, recurring billing, payment match.',
 'Generate GST-compliant invoices, e-invoice IRNs via the official IRP, and reconcile incoming payments automatically. Built around the workflow of a small accountancy practice.',
 'Business Tools', 6999, 79, '#60a5fa',
 'React,Spring Boot,GST API',
 'GST-compliant invoices (B2B/B2C)|E-invoice IRN via IRP|Recurring + retainer billing|Payment reconciliation|Vendor master + TDS handling|Tally / Zoho Books export',
 'Complete source|GST rate master|IRP integration guide|Setup video',
 'React,Spring Boot,PostgreSQL,GST IRP',
 24, '2.0.1', NULL, NULL, TRUE),

('shivhari-dev-template',
 'Cinematic Portfolio Template',
 'The exact site you''re on — scroll-driven cinema, R3F 3D scenes, store + admin included.',
 'Drop in your name, your projects, your frame sequence, your colours. Designed to brand-customize in under 30 minutes. React + Vite + R3F + Framer Motion + GSAP frontend, Spring Boot backend with store + admin.',
 'Templates', 3999, 49, '#60a5fa',
 'React,Vite,R3F,GSAP,Spring Boot',
 'Scroll-driven frame sequences|R3F 3D ambient scenes|Bento grid project showcase|Cart-ready store routes|Admin dashboard included|Spring Boot backend bundled',
 'Complete React + Spring Boot source|Setup guide + deploy scripts|Free updates for 12 months',
 'React 18,Vite,TypeScript,Tailwind,R3F,Framer Motion,Spring Boot',
 14, '1.0.0', 'https://shivhari.dev', NULL, TRUE),

('cafe-pos',
 'Sugar & Spice Café POS',
 'POS + inventory + CRM automation built for my own café. Battle-tested in production.',
 'Tablet-friendly POS, automated inventory thresholds, lightweight customer CRM. Owner-operator product — just the source code, no SaaS lock-in.',
 'Business Tools', 9999, 129, '#10b981',
 'React,Node,PostgreSQL,POS',
 'Tablet-first POS UI|Inventory thresholds + reorder alerts|Customer CRM|Daily/weekly reports|Offline-tolerant transactions',
 'Complete source code|Sample seed for a café|PDF receipt template|Setup guide|Email support 30 days',
 'React,Node 20,PostgreSQL,Tailwind',
 41, '1.0.4', NULL, NULL, FALSE),

('autoscalp-bot',
 'AutoScalp Trading Bot',
 'Algorithmic options-scalping engine for the Indian equity market.',
 'Low-latency Java + WebSocket order routing. Parameter-sweep backtesting + walk-forward validation. Bring your own broker credentials.',
 'Trading & Quant', 14999, 199, '#fbbf24',
 'Java,Spring WebFlux,Redis,TimescaleDB',
 'Order routing under 20ms p99|Parameter-sweep backtesting harness|Walk-forward validation|Kite Connect broker adapter|Web UI with real-time P&L',
 'Complete source|Backtest data sample (3 mo)|Strategy presets|Setup video walkthrough',
 'Java 17,Spring WebFlux,React,Redis,TimescaleDB',
 64, '2.5.0', NULL, NULL, FALSE),

('workiva-toolkit',
 'Workiva Integration Toolkit',
 'Reusable Java connectors for Salesforce ↔ Wdesk, audit trail, scheduled refresh.',
 'The connectors I built across multiple Workiva rollouts, packaged. SOX-friendly audit trail out of the box.',
 'Enterprise', 19999, 249, '#38bdf8',
 'Workiva,Salesforce,Java,AWS Lambda',
 'Salesforce → Wdesk sync|Scheduled refresh via Lambda|Audit trail (SOX-friendly)|Configurable column mapping|Connector unit-test fixtures',
 'Complete source|Workiva API client|Salesforce client|Setup videos',
 'Java 17,Spring Boot,AWS Lambda,Salesforce API,Workiva SDK',
 22, '3.0.1', NULL, NULL, FALSE);
